services:
  - type: web
    name: cleanocean-live
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: ADMIN_TOKEN
        sync: false
